#ifndef __VERSION_H__
#define __VERSION_H__
#define VERSION_DATE "Tue, 20 Sep 2016 14:12:38 +0000"
#define VERSION_HASH "UNKNOWN"
#define VERSION_BRANCH "UNKNOWN"
#define VERSION_REPO "UNKNOWN"
#endif
