#include "IptablesUtil.h"

void IptablesUtil::update(const AnsiString& str) {
  Logger::log("[IptablesUtil][update]");
  ShellUtil::exec("sudo echo \"" + str + " \" | iptables-restore");
  Logger::log("[IptablesUtil] update done");
}

AnsiString IptablesUtil::genDefaultString(const AnsiString& dstIface, const DynSet<AnsiString>& srcIface) {
  AnsiString ret = "";
  ret += "# Generated by iptables-save v1.4.21 on Fri Mar 11 00:00:00 2016\n";
  ret += "*filter\n";
  ret += ":INPUT ACCEPT [47:6276]\n";
  ret += ":FORWARD ACCEPT [41:14704]\n";
  ret += ":OUTPUT ACCEPT [28:3681]\n";
  for(int i=0;i<srcIface.Size();i++)
    if(srcIface[i] != "") {
      ret += "-A FORWARD -i " + srcIface[i] + " -j ACCEPT\n";
    }
  ret += "COMMIT\n";
  ret += "# Completed on Fri Mar 11 13:22:04 2016\n";
  ret += "# Generated by iptables-save v1.4.21 on Fri Mar 11 00:00:00 2016\n";
  ret += "*nat\n";
  ret += ":PREROUTING ACCEPT [38:3270]\n";
  ret += ":INPUT ACCEPT [12:1776]\n";
  ret += ":OUTPUT ACCEPT [4:473]\n";
  ret += ":POSTROUTING ACCEPT [3:377]\n";
  ret += "-A POSTROUTING -o " + dstIface +" -j MASQUERADE\n";
  ret += "COMMIT\n";
  ret += "# Completed on Fri Mar 11 00:00:00 2016";
  return ret;
}

void IptablesUtil::setDefault(const AnsiString& dstIface, const DynSet<AnsiString>& srcIface) {
  update(genDefaultString(dstIface, srcIface));
}

